### ISSUE TITLE
Failed Password Not Recognized

### ISSUE THREAD

**Issue by B2RN** [wazuh/ossec-rules#22]
A pretty typical message from "/var/log/auth.log" doesn't seem to be recognized. This makes it difficult to wrap/filter out the rule, since it falls under the category of rule 1002:

Rule: 1002 fired (level 2) -> "Unknown problem somewhere in the system."

This is the message that doesn't seem to be caught properly:

May 23 11:27:29 a.b sshd[28184]: message repeated 2 times: [ Failed password for root from a.b.c.d port 38836 ssh2]

Our ruleset is updated daily. Let me know if you need any further info, or any action from my side.

Cheers

**Comment by jesuslinares** [comment]
Hi,

what OS are you running?. I recommend you to disable that kind of logs (if it is possible). It think it is useless (like the message: "last message repeated X times"). OSSEC is able to detect when an user fails to login repeatedly. Also, I think other log analysis tool will not handle this correctly.

We would have to rewrite a lot of decoders and rules to support these messages. Do you think it is really necessary?.

In case you need it for a specific event, send an email with your case to wazuh list and we can help you.

Thanks.

**Comment by B2RN** [comment]
I'm running CentOS 7.2. But yeah, you're right. Not at the server at the moment, but the message I mentioned is followed by a properly recognized PAM message, tied to a recognized rule. At least that's what I remember.

I'll take a look at whether the message can be disabled, and where it's coming from. I'll drop a line here if I figure it out.

Cheers for the idea.

**Comment by B2RN** [comment]
So what worked for me was the following in /etc/rsyslog.conf

$RepeatedMsgReduction off

The default being on. Done on several Ubuntu 14.04 agents. Seems to be working, so I'll close the ticket.

**Comment by jesuslinares** [comment]
Thank you, very useful.
