### ISSUE TITLE
It would be nice to not have to destroy the cloudtrail logs while loading

### ISSUE THREAD

**Issue by jstelzer** [wazuh/ossec-rules#26]
The existing log processor doesn't scale when you have a lot of logs and do not wish to delete them.

See https://github.com/wazuh/ossec-rules/pull/25 for a proposed patch to address this.

sqlite3 is core python2.7

**Comment by snaow** [comment]
Totally right. Merged and closed on https://github.com/wazuh/ossec-rules/pull/25.

Thanks again for your contribution.
